name: WorldBackupManager
version: 1.0.0
main: slyss0fly\WorldBackupManager\Main
api: 5.0.0
author: skyss0fly
commands:
  backup:
    description: "Manually backup the world."
    permission: backup.use
  restore:
    description: "Restore a Backup."
    permission: backup.restore

permissions:
  backup.use:
    description: "Manually Backup the world."
    default: op
  backup.restore:
    description: "Restore a Backup."
    default: op
